skinTone: original
hairColor: original
irisColor: original
base: /parts/billy-head.yml @0,0,290,400
parts:
  - /parts/billy-eyes.yml @25,150
  - /parts/billy-mouth.yml @20,290
  - /parts/billy-nose.yml @94,200
